import PDFDocument from 'pdfkit';
import { format } from 'date-fns';
import { fromMinorUnits } from '../../shared/utils/money';
import { Currency } from '../../shared/types';
import { TransactionWithCategory } from '../transactions/transaction.repository';
import { FinancialSummary } from '../analytics/analytics.service';

/** PDF-safe money formatter — uses ISO code instead of symbol (avoids font glyph issues). */
function pdfMoney(amountMinor: bigint, currency: Currency): string {
  const major = fromMinorUnits(amountMinor, currency);
  return `${currency} ${major.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export async function generatePDF(
  transactions: TransactionWithCategory[],
  summary: FinancialSummary,
  userName: string,
): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const cur = summary.currency as Currency;
    const col2 = 300;

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('Financial Report', { align: 'center' });
    doc.fontSize(11).font('Helvetica').text(`${userName} — ${summary.label}`, { align: 'center' });
    doc.moveDown();

    // Summary
    doc.fontSize(14).font('Helvetica-Bold').text('Summary');
    doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(1).stroke();
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');

    doc.text('Income:', 50); doc.moveUp(); doc.text(pdfMoney(summary.income, cur), col2); doc.moveDown(0.3);
    doc.text('Expenses:', 50); doc.moveUp(); doc.text(pdfMoney(summary.expenses, cur), col2); doc.moveDown(0.3);

    const netSign = summary.net >= 0n ? '+' : '-';
    const absNet = summary.net < 0n ? -summary.net : summary.net;
    doc.font('Helvetica-Bold').text('Net:', 50);
    doc.moveUp();
    doc.text(`${netSign}${pdfMoney(absNet, cur)}`, col2);
    doc.font('Helvetica').moveDown();

    // Category breakdown
    if (summary.byCategory.length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Spending by Category');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(1).stroke();
      doc.moveDown(0.5);

      for (const cat of summary.byCategory.slice(0, 10)) {
        doc.fontSize(11).font('Helvetica');
        doc.text(cat.categoryName, 50); doc.moveUp();
        doc.text(`${pdfMoney(cat.total, cur)}  (${Math.round(cat.percentage)}%)`, col2);
        doc.moveDown(0.3);
      }
      doc.moveDown();
    }

    const renderTableHeader = () => {
      doc.fontSize(9).font('Helvetica-Bold');
      const headerY = doc.y;
      doc.text('Date', 50, headerY, { width: 70 });
      doc.text('Type', 122, headerY, { width: 50 });
      doc.text('Category', 174, headerY, { width: 85 });
      doc.text('Description', 261, headerY, { width: 174 });
      doc.text('Amount', 437, headerY, { width: 108, align: 'right' });
      doc.y = headerY + 13;
      doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(0.5).stroke();
      doc.moveDown(0.4);
    };

    // Transactions table
    if (transactions.length > 0) {
      const txCount = transactions.length;
      doc.fontSize(14).font('Helvetica-Bold').text(`Transactions (${txCount})`);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(1).stroke();
      doc.moveDown(0.5);

      renderTableHeader();

      doc.fontSize(8).font('Helvetica');
      const descWidth = 174;
      const txList = transactions.slice(0, 1000);

      for (const tx of txList) {
        const sign = tx.type === 'INCOME' || tx.type === 'REFUND' ? '+' : '-';
        const descText = tx.description || '';
        const descHeight = doc.heightOfString(descText, { width: descWidth });
        const rowHeight = Math.max(descHeight, 11);

        // Check if row fits on current page (leave 60pt for footer)
        if (doc.y + rowHeight > doc.page.height - 60) {
          doc.addPage();
          renderTableHeader();
          doc.fontSize(8).font('Helvetica');
        }

        const rowY = doc.y;
        doc.text(format(tx.transactionDate, 'MMM d, yyyy'), 50, rowY, { width: 70 });
        doc.text(tx.type, 122, rowY, { width: 50 });
        doc.text(tx.category?.name ?? 'Other', 174, rowY, { width: 85 });
        doc.text(descText, 261, rowY, { width: descWidth });
        doc.text(`${sign}${pdfMoney(tx.amountMinor, cur)}`, 437, rowY, { width: 108, align: 'right' });

        doc.y = rowY + rowHeight + 3;
      }
    }

    // Footers on all buffered pages
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(8).font('Helvetica').text(
        `Generated by Expense Bot · Page ${i + 1} of ${range.count} · ${format(new Date(), 'MMM d, yyyy HH:mm')}`,
        50,
        doc.page.height - 40,
        { align: 'center', width: 495 },
      );
    }

    doc.end();
  });
}
