import PDFDocument from 'pdfkit';
import { format } from 'date-fns';
import { fromMinorUnits } from '../../shared/utils/money';
import { Currency } from '../../shared/types';
import { TransactionWithCategory } from '../transactions/transaction.repository';
import { FinancialSummary } from '../analytics/analytics.service';

/** PDF-safe money formatter — uses ISO code instead of symbol (avoids font glyph issues). */
function pdfMoney(amountMinor: bigint, currency: Currency): string {
  const major = fromMinorUnits(amountMinor, currency);
  return `${currency} ${major.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export async function generatePDF(
  transactions: TransactionWithCategory[],
  summary: FinancialSummary,
  userName: string,
): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const cur = summary.currency as Currency;
    const col2 = 300;

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('Financial Report', { align: 'center' });
    doc.fontSize(11).font('Helvetica').text(`${userName} — ${summary.label}`, { align: 'center' });
    doc.moveDown();

    // Summary
    doc.fontSize(14).font('Helvetica-Bold').text('Summary');
    doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(1).stroke();
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');

    doc.text('Income:', 50); doc.moveUp(); doc.text(pdfMoney(summary.income, cur), col2); doc.moveDown(0.3);
    doc.text('Expenses:', 50); doc.moveUp(); doc.text(pdfMoney(summary.expenses, cur), col2); doc.moveDown(0.3);

    const netSign = summary.net >= 0n ? '+' : '-';
    const absNet = summary.net < 0n ? -summary.net : summary.net;
    doc.font('Helvetica-Bold').text('Net:', 50);
    doc.moveUp();
    doc.text(`${netSign}${pdfMoney(absNet, cur)}`, col2);
    doc.font('Helvetica').moveDown();

    // Category breakdown
    if (summary.byCategory.length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Spending by Category');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(1).stroke();
      doc.moveDown(0.5);

      for (const cat of summary.byCategory.slice(0, 10)) {
        doc.fontSize(11).font('Helvetica');
        doc.text(cat.categoryName, 50); doc.moveUp();
        doc.text(`${pdfMoney(cat.total, cur)}  (${Math.round(cat.percentage)}%)`, col2);
        doc.moveDown(0.3);
      }
      doc.moveDown();
    }

    // Transactions table
    if (transactions.length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text(`Transactions (${Math.min(transactions.length, 100)})`);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(1).stroke();
      doc.moveDown(0.5);

      doc.fontSize(9).font('Helvetica-Bold');
      doc.text('Date', 50, doc.y, { width: 75 }); doc.moveUp();
      doc.text('Type', 125, doc.y, { width: 65 }); doc.moveUp();
      doc.text('Category', 190, doc.y, { width: 100 }); doc.moveUp();
      doc.text('Description', 290, doc.y, { width: 145 }); doc.moveUp();
      doc.text('Amount', 435, doc.y, { width: 110, align: 'right' });
      doc.moveDown(0.4);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(0.5).stroke();
      doc.moveDown(0.3);

      doc.fontSize(8).font('Helvetica');
      for (const tx of transactions.slice(0, 100)) {
        const sign = tx.type === 'INCOME' || tx.type === 'REFUND' ? '+' : '-';
        doc.text(format(tx.transactionDate, 'MMM d, yyyy'), 50, doc.y, { width: 75 }); doc.moveUp();
        doc.text(tx.type, 125, doc.y, { width: 65 }); doc.moveUp();
        doc.text(tx.category?.name ?? 'Other', 190, doc.y, { width: 100 }); doc.moveUp();
        doc.text(tx.description.slice(0, 22), 290, doc.y, { width: 145 }); doc.moveUp();
        doc.text(`${sign}${pdfMoney(tx.amountMinor, cur)}`, 435, doc.y, { width: 110, align: 'right' });
        doc.moveDown(0.3);
      }
    }

    // Footer
    doc.fontSize(8).font('Helvetica').text(
      `Generated by Expense Bot · ${format(new Date(), 'MMM d, yyyy HH:mm')}`,
      50, doc.page.height - 50, { align: 'center', width: 495 },
    );

    doc.end();
  });
}
